DocxGen = require('./docxgen')
DocxGen.PptxGen=require('./pptxgen')
DocxGen.DocUtils=require('./docUtils')
DocxGen.ModuleManager=require('./moduleManager')
DocxGen.XmlTemplater=require('./xmlTemplater')
DocxGen.XmlMatcher=require('./xmlMatcher')
DocxGen.XmlUtil=require('./xmlUtil')
DocxGen.SubContent=require('./subContent')
module.exports=DocxGen
